### ISSUE TITLE
timeseriesvalues should but upserted and not duplicated when QC values change.

### ISSUE THREAD

**Issue by ZofiaRudjord** [NIVANorge/odm2-postgres-api#120]
insert_timeseries_resultvalues will create a duplicate if data are ingested with updated QC value.
This should be changed to upsert.

**Comment by ZofiaRudjord** [comment]
Currently there is the following unique constraint on the TimeSeriesResultValues: 
UNIQUE (ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, QualityCodeCV, TimeAggregationInterval, TimeAggregationIntervalUnitsID));

This means that if we update the QC flag ( eg due to changing thresholds ) we will end up having 
for the same timeseries type ( e.g. temp) for a given timestamp, value pair two rows: with good and with bad qc.
This makes no sense. 

Do you know if this constraint was created by Roald or automatically generated @haakondr ?
If later what is the purpose of it?

I suggest to alter it to:
UNIQUE (ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationIntervalUnitsID));
and update QualityCodeCV when re-running QC.
Before I proceed with modyfying this unique constraints I would like to hear your opinion on this @haakondr @knl88 @jemmima

**Comment by haakondr** [comment]
Agree to changing the unique constraint to how you propose. Does not make sense to include QualityCodeCV in the constraint.

according to git history this comes from when Roald copied over the odm2 schema "as is".
