### ISSUE TITLE
Setup kafka environment for on-prem sync

### ISSUE THREAD

**Issue by haakondr** [NIVANorge/odm2-postgres-api#32]
## background

we need a way to keep our cloud and on-premise environments in sync. Data entered in cloud UI's and sensors should in many cases also land in nivabase. The purpose of this issue is to give some background to the design choices made to achieve this.

Some very different approaches:

## 1. Modernise current on-premise applications
This is in many cases the best alternative IF we want feature parity. The alternative would be to lift/modernise parts of the tech stack in layers. A migration path could look something like the following:

1. migrate from oracle -> postgres with 1:1 data model
2. Move to cloud
3. modernise web applications

### pros
- Active users from day 1
- builds on a battle-proven application code 

### cons

- may be hard to do bigger changes
- Would have to do a lot of time investments on maybe the wrong things (like, further improving our oracle database as opposed to moving out of it)

## 2. Expose API's or databases from on-premise

Another alternative would be to expose nivabase or API's externally to the cloud. This would probably be the fastest way to sync up, but we also expose our on-premise infrastructure to our cloud environment, which could have security consequences. Also, we would then invest quite a lot of time to further build/modernise nivabase etc. 

### Pros

- probably fastest "time to market"

### Cons

- response times may not be great
  - due to latency between data centers, but also due to current code/database setup that is less agile for change
- further investment into current infrastructure. oracle license costs + on-prem servers needs maintenance (even though we move to USIT, this still comes as a cost)

Given the above two alternatives 

One of the main design choices we have to make is whether we put everything behind a kafka stream, or we use kafka to sync up the databases. Some alternatives:

## 3. async event-driven data flow

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgS2Fma2EgLS0-IG9kbTJbKE9ETTIpXVxuICBLYWZrYSAtLT4gbml2YWJhc2VbKE5pdmFiYXNlKV1cbiAgQXF1YW1vbml0b3IgLS0-IEthZmthXG4gIEJlZ3JvaW5nIC0tPiBLYWZrYVxuICBMYWIvTGFid2FyZSAtLT4gS2Fma2FcbiAgU2Vuc29ycyAtLT4gS2Fma2FcbiAgRmVycnlib3ggLS0-IEthZmthIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgS2Fma2EgLS0-IG9kbTJbKE9ETTIpXVxuICBLYWZrYSAtLT4gbml2YWJhc2VbKE5pdmFiYXNlKV1cbiAgQXF1YW1vbml0b3IgLS0-IEthZmthXG4gIEJlZ3JvaW5nIC0tPiBLYWZrYVxuICBMYWIvTGFid2FyZSAtLT4gS2Fma2FcbiAgU2Vuc29ycyAtLT4gS2Fma2FcbiAgRmVycnlib3ggLS0-IEthZmthIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)

Here, we put everything behind kafka, and we fully adopt an async event-driven architecture. I think this is the ideal situation, but we need to make sure that we can really trust our products.

### pros
- data writes can come from anywhere. This allows us to write new stations either from aquamonitor or a new interface, while data flow into both databases
- Migration path from nivabase to odm2 becomes much easier by just migrating to using kafka we can gradually move one process at a time
- by going for a data streaming architecture, we can more easily build data products that are updated real time. 

### cons
- interacting with async systems may not always yield the best user experience and is something that we should be aware of. For instance, if a user creates a new station, he/she may not immediately see it in the user interface on refresh (unless we create some kind of temporary state)
- ideally, our kafka stream is persistent with infinite retention. This is possible, but I don't have enough detailed knowledge about kafka to really see the cons of this approach
- data model changes might be more complicated if we go for infinite retention. Need to think through this carefully so that we are able to change our data model
- more application code potentially needs to be rewritten (but this is probably also safer). Could also use kafka connect in cases where we don't want to change application code

## 4. ODM2 as primary, sync with kafka

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgYmVncm9pbmcgLS0-IG9kbTJbKE9ETTIpXVxuICBvZG0yIC0tPiBrYWZrYVxuICBrYWZrYSAtLT4gbml2YWJhc2VcbiAgbml2YWJhc2UgLS0-IGthZmthXG4gIGthZmthIC0tPiBvZG0yIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgYmVncm9pbmcgLS0-IG9kbTJbKE9ETTIpXVxuICBvZG0yIC0tPiBrYWZrYVxuICBrYWZrYSAtLT4gbml2YWJhc2VcbiAgbml2YWJhc2UgLS0-IGthZmthXG4gIGthZmthIC0tPiBvZG0yIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)
Slightly more old-school way of syncing data. All data entered into ODM2 will get synced using something like kafka connect. 

### pros

- User interface will be synchronous, the user will see their station on refresh
- less code change, as this is more or less the setup we have today.

### cons

-  two-way writes become more complicated (writes from both aquamonitor and new UI's). I'd say that this design excludes writing to ODM2 from aquamonitor, which in turn forces us to opt for a less agile migration
- more integrations to keep in sync. Changing our ODM2 data model means that we need to update a nivabase integration)
- the ODM2 data model needs to contain all the data required to sync to the nivabase datamodel. This could potentially be a big technical debt 

## Summary

We have sort of started out on the path of alternative 3 or 4, with a separate postgres database running in the cloud using ODM2 data model. This is definitely a good opportunity to revisit that strategy.

With that in mind, I believe that moving on with ODM2 looks promising, and I would like to either go for alternative 3 or 4. I believe both are about as much work, but if we want to have two-way writes (wrote both from cloud and on-prem) I think we should go for alternative 3 (async event-driven)

## questions

Kafka-specific:

- I think we should use a managed kafka environment from a 3rd party, but we should be able to opt-out of this and run in our own infrastructure. How easy is this?
- how is error handling done? Can we mark messages as failed (NACK) to be picked up at later time (dead letter queue, DLQ) ?
- what is message/record acknowledge (ack) timeout?
  - google pubsub has a limitation of 10 mins ack timeout, which means that our processing has to complete by 10 mins
- is it feasible with infinite retention? Is it a good idea? what would cost over time be?
- is there any message prioritisation concept? We'd like to prioritise live data over batch ingestion, for instance
- how is the python, node and R clients to kafka? Kafka is sprung out of java-land. Hopefully the other language clients are good enough
- is it possible to query our kafka stream for data? 
  - as in, can we query based on the message data and timestamps, not only their offsets (time of entry to kafka). I suspect ksqldb is the answer to this
  - For python there is kafka-python but also https://github.com/confluentinc/confluent-kafka-python which might be faster as it uses less python for the job (seemingly)

**Comment by haakondr** [comment]
I have setup a kafka environment using confluent cloud. Confluent has the option to run in google cloud data centers and also integrates with google cloud billing. I have not yet setup any kind of SSO, so for now I'll have to invite specific users for access.

Ideally we setup SSO with either google cloud niva.no organisation or github SSO

**Comment by haakondr** [comment]
> * is there any message prioritisation concept? We'd like to prioritise live data over batch ingestion, for instance

Does not seem like there is a possibility to prioritise records/messages, and people seem to do this by having separate topics (similar to how we have currently done this using google pub/sub).

**Comment by bennoniva** [comment]
Sounds good, please keep me in the loop on Kafka/ksql. Takk.

**Comment by haakondr** [comment]
## Error handling

Kafka consumers may auto-commit messages. This is done on an interval and may lead to unwanted behaviour. I think we should manually commit each message. I think our consumers should do the following (very simplified):

```
def consume_message(msg):
  try:
    # process message
    # after successfully processing, commit:
    consumer.commit() 
  except:  
    # log error, no commit
```

this way, our consumer process does not crash, logging errors and leave message. 

What should then happen? Ideally, I think the message should be retried a couple times (3?). Often errors are due to downtime or flaky network services. If a message is not successfully commited after retries, it needs to be put on a separate error handling queue (dead letter queue, DLQ).

**Comment by jemmima** [comment]
> ideally, our kafka stream is persistent with infinite retention. This is possible, but I don't have enough detailed knowledge about kafka to really see the cons of this approach

Why do we want this? I don't think kafka is intended to act as an audit log or source of truth is it?

**Comment by haakondr** [comment]
> Why do we want this? I don't think kafka is intended to act as an audit log or source of truth is it?

well, it depends. I think it is possible. saw a talk from finn.no and it seems like they are exactly doing this: https://www.youtube.com/watch?v=OxAt1Am7exg

I can see two big drawbacks:

- storage costs may be high, need to do some estimates
- data model changes may be tricky since our kafka log is immutable

**Comment by jemmima** [comment]
see https://github.com/NIVANorge/niva-data-producers
